name: CI-clean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_integration:
        description: 'Set to "true" to run integration steps that may exercise hardware-adjacent code'
        required: false
        default: 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint (flake8)
        run: flake8 .
      - name: Run unit tests
        run: python -m unittest discover -v

  integration:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.run_integration == 'true') }}
    env:
      RUN_HARDWARE_INTEGRATION: ${{ github.event.inputs.run_integration }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install runtime dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Smoke-run (prints detected optional deps)
        run: python -m src.main
      - name: Device example (best-effort)
        run: python -m src.device.example || true
      - name: Run hardware integration tests
        run: python -m unittest tests.test_integration_hardware -v
